fun main() {
    println("EJERCICIO 1.-")
    ejercicio01()
    println("----------------------------------------------------")
    println("EJERCICIO 2.-")
    ejercicio02()
    println("----------------------------------------------------")
    println("EJERCICIO 3.-")
    ejercicio03()
    println("----------------------------------------------------")
    println("EJERCICIO 4.-")
    ejercicio04()
    println("----------------------------------------------------")
    println("EJERCICIO 5.-")
    ejercicio05()
    println("----------------------------------------------------")
    println("EJERCICIO 6.-")
    ejercicio06()
    println("----------------------------------------------------")
}